baseURL: https://gestoriasbaratas.es
languageCode: en-us
title: Gestorias Barata
theme: hugo-fresh
publishDir: docs


params:
  logo: /images/logos/fresh-alt.svg
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Gestorias de empresas en toda España. Creación gratuita en 72 horas.
    # Hero subtitle (optional)
    subtitle: Te vendras por el precio. Te quedarás por nuestros servicios.
    # Button text
    buttontext: Contactanos
    # Where the main hero button links to
    buttonlink: "#contacto"
    # Hero image (from /images/___)
    image: illustrations/salesman.jpg
    # Footer logos (from /images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Productos
    url: "#productos"
  - title: Servicios
    url: "#servicios"
  - title: Contacto
    url: "#contacto"
    button: true

  section1:
    ancor: productos
    title: Nuestros productos
    subtitle: Ahorro asegurado
    tiles:
    - title: Creación de una SL
      icon: plug-cloud
      text: Ahorra mas de 700€ y crea tu SL gratis, en 72 horas, cerca de tu casa
    - title: Gestion empresarial completa
      icon: mouse-globe
      text: A partir de 90€/mes, gestionamos facturas, recibos, impuestos de manera sencilla y transparente para el cliente
  section2:
    ancor: servicios
    title: Una nueva asesoria
    subtitle: Desde el primer momento, notarás la diferencia
    features:
    - title: Gestion completa
      text: "Nuestro equipo cubre todos los servicios de gestoria para una empresa: contabilidad, impuestos, declaraciones, pagos, libros y cuentas."
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Informes
      text: Entregamos balance de perdidas/ganancias, balance de situación, balance de sumas/saldos, y todos los informes periodicos que el cliente necesita, en diferentes formatos digitales (XLS o PDF)
      icon: doc-sync
    - title: Herramientas de trabajo
      text: Trabajamos con software que permite de gestionar facturas, pagos e informes te forma compartida con el cliente, para facilitar las operaciones diarias, mensuales y anuales. Nuestra plataforma tambien permite de gestionar facturas y recibos desde movil.
      icon: mobile-feed
  # Main CTA - disabled for now
  # section3:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"

  # Testimonials - TODO in the future
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    footerlinks:
    - text: Aviso Legal
      link: /legal
    - text: Política de Privacidad
      link: /privacidad
    - text: Condiciones de contratación
      link: /contratacion
    - text: Política de Cookies
      link: /politica-cookies
    - text: Aceptación
      link: /aceptacion
