baseURL: https://gestoriasbaratas.es
languageCode: en-us
title: Gestorias Baratas
theme: hugo-fresh
publishDir: docs


params:
  jivoid: FmrIdswqLT
  analyticsid: UA-31737927-2
  logo: /images/logos/gestoriasbarata.png
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    title: GestoriasBaratas.es - Gestion de empresas en toda España. Creación gratuita en 72 horas.
    subtitle: Te vendras por el precio. Te quedarás por nuestros servicios.
    buttontext: Contactanos
    buttonlink: "#contacto"
    image: illustrations/multitasking.png
  navbar:
  - title: Productos
    url: "#productos"
  - title: Servicios
    url: "#servicios"
  - title: Contacto
    url: "#contacto"
    button: true

  products:
    ancor: productos
    title: Nuestros productos
    subtitle: Ahorro asegurado
    tiles:
    - title: Creación de una empresa (SL)
      icon: laptop-cloud
      buttonText: Gratis!
      url: "#contacto"
      text: Ahorra mas de 700€ y crea tu empresa gratis, en menos de 72 horas, y puedes firmar cerca de tu casa.
    - title: Gestion empresarial completa
      icon: mouse-globe
      buttonText: 90€/mes
      url: "#contacto"
      text: A partir de 90€/mes, gestionamos facturas, recibos e impuestos de tu empresa, de forma rápida y transparente.
    - title: Tu consultoria a medida
      icon: plug-cloud
      buttonText: a medida
      url: "#contacto"
      text: Explicanos tus necesidades y te proporcionamos soluciones; la primera hora es gratis, sin compromiso.
  services:
    ancor: servicios
    title: Una nueva asesoria
    subtitle: Hablamos tu idioma, utilizamos las mejores tecnologias como parte de nuestro proceso diario. Desde el primer momento, notarás la diferencia con otras asesorias.
    features:
    - title: Gestion completa
      text: "Nuestro equipo cubre todos los servicios de gestoria para una empresa: contabilidad, impuestos, declaraciones, pagos, libros y cuentas."
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Informes
      text: Entregamos balance de perdidas/ganancias, balance de situación, balance de sumas/saldos, y todos los informes periodicos que el cliente necesita, en diferentes formatos digitales (XLS o PDF).
      icon: doc-sync
    - title: Herramientas de trabajo
      text: Trabajamos con software que permite de gestionar facturas, pagos e informes te forma compartida con el cliente, para facilitar las operaciones diarias, mensuales y anuales. Nuestra plataforma tambien permite de gestionar facturas y recibos desde movil.
      icon: mobile-feed
  technologies:
  - appearin
  - whatsapp
  - googlesuite
  - paypal
  - waveapps
  footer:
    # Logo (from /images/logos/___)
    logo: gestoriasbarata.png
    footerlinks:
    - id: legal
      linkname: Aviso Legal
    - id: privacidad
      linkname: Política de Privacidad